# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------
title: NumericalSteepestDescent.jl
author: Thomas Caussade
url: "https://tcaussade.github.io"
baseurl: "/NumericalSteepestDescent.jl"

# -----------------------------------------------------------------------------
# Build & Theme Settings
# -----------------------------------------------------------------------------
theme: jekyll-theme-primer # A clean, responsive theme that fits documentation well

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# -----------------------------------------------------------------------------
# Markdown & Rendering Configurations
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  mathengine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
